ct2_model_path: ct2/ct2-nllb-200-3.3B-int8
sp_model_path: sp/sentencepiece.bpe.model
comet_model_name: Unbabel/wmt22-comet-da
src_lang: en
tgt_lang: am
dataset:
  path: facebook/flores
  src_config: "eng_Latn"
  tgt_config: "amh_Ethi"
  text_col: "sentence"
  split: devtest
log_file: logs/en_am_eval.log